[2024-03-29T19:21:27.788+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:21:27.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:21:27.791+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:21:27.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:21:27.805+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:21:27.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:21:27.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:21:27.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.050 seconds
[2024-03-29T19:21:58.459+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:21:58.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:21:58.462+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:21:58.461+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:21:58.470+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:21:58.468+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:21:58.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:21:58.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.030 seconds
[2024-03-29T19:22:28.706+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:22:28.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:22:28.709+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:22:28.709+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:22:28.721+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:22:28.718+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:22:28.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:22:28.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.050 seconds
[2024-03-29T19:22:58.965+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:22:58.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:22:58.967+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:22:58.967+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:22:58.978+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:22:58.975+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:22:58.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:22:59.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.042 seconds
[2024-03-29T19:23:29.212+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:23:29.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:23:29.216+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:23:29.216+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:23:29.234+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:23:29.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:23:29.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:23:29.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.072 seconds
[2024-03-29T19:23:59.451+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:23:59.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:23:59.453+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:23:59.453+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:23:59.466+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:23:59.462+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:23:59.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:23:59.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.061 seconds
[2024-03-29T19:27:45.015+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:27:45.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:27:45.018+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:27:45.018+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:27:45.035+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:27:45.032+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils.yaml_loader import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:27:45.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:27:45.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.043 seconds
[2024-03-29T19:28:15.627+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:28:15.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:28:15.629+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:28:15.629+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:28:15.647+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:28:15.635+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils.yaml_loader import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:28:15.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:28:15.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.040 seconds
[2024-03-29T19:28:45.870+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:28:45.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:28:45.873+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:28:45.873+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:28:45.893+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:28:45.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils.yaml_loader import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:28:45.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:28:45.913+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.047 seconds
[2024-03-29T19:29:16.128+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:29:16.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:29:16.132+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:29:16.131+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:29:16.145+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:29:16.142+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils.yaml_loader import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:29:16.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:29:16.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.054 seconds
[2024-03-29T19:29:46.403+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:29:46.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:29:46.407+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:29:46.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:29:46.421+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:29:46.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils.yaml_loader import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:29:46.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:29:46.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.046 seconds
[2024-03-29T19:30:16.661+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T19:30:16.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T19:30:16.665+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:30:16.664+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T19:30:16.674+0000] {logging_mixin.py:188} INFO - [2024-03-29T19:30:16.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from ..python.utils.yaml_loader import load_yaml
ImportError: attempted relative import with no known parent package
[2024-03-29T19:30:16.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T19:30:16.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.043 seconds
[2024-03-29T20:07:49.657+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:07:49.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:07:49.668+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:07:49.667+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:07:49.692+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:07:49.689+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from highliner.utils import load_yaml
ModuleNotFoundError: No module named 'highliner'
[2024-03-29T20:07:49.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:07:49.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.089 seconds
[2024-03-29T20:08:20.302+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:08:20.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:08:20.305+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:08:20.305+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:08:20.315+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:08:20.313+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from highliner.utils import load_yaml
ModuleNotFoundError: No module named 'highliner'
[2024-03-29T20:08:20.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:08:20.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.035 seconds
[2024-03-29T20:08:50.583+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:08:50.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:08:50.585+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:08:50.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:08:50.605+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:08:50.603+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from highliner.utils import load_yaml
ModuleNotFoundError: No module named 'highliner'
[2024-03-29T20:08:50.607+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:08:50.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.058 seconds
[2024-03-29T20:09:20.835+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:09:20.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:09:20.839+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:09:20.838+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:09:20.880+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:09:20.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from highliner.utils import load_yaml
ModuleNotFoundError: No module named 'highliner'
[2024-03-29T20:09:20.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:09:20.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.118 seconds
[2024-03-29T20:09:51.144+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:09:51.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:09:51.146+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:09:51.146+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:09:51.157+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:09:51.155+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from highliner.utils import load_yaml
ModuleNotFoundError: No module named 'highliner'
[2024-03-29T20:09:51.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:09:51.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.038 seconds
[2024-03-29T20:10:21.393+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:10:21.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:10:21.395+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:10:21.395+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:10:21.404+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:10:21.403+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 4, in <module>
    from highliner.utils import load_yaml
ModuleNotFoundError: No module named 'highliner'
[2024-03-29T20:10:21.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:10:21.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.036 seconds
[2024-03-29T20:31:24.055+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:31:24.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:31:24.059+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:31:24.059+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:31:24.072+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:31:24.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 2, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-03-29T20:31:24.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:31:24.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.040 seconds
[2024-03-29T20:31:54.704+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:31:54.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:31:54.708+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:31:54.707+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:31:54.721+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:31:54.719+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 2, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-03-29T20:31:54.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:31:54.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.055 seconds
[2024-03-29T20:32:25.028+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:32:25.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:32:25.031+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:32:25.030+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:32:25.042+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:32:25.040+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 2, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-03-29T20:32:25.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:32:25.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.034 seconds
[2024-03-29T20:32:55.271+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:32:55.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:32:55.274+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:32:55.273+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:32:55.285+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:32:55.283+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 2, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-03-29T20:32:55.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:32:55.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.045 seconds
[2024-03-29T20:39:57.184+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:39:57.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:39:57.188+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:39:57.188+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:39:57.238+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:39:57.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 7, in <module>
    class GenericDAG(ABC, BaseModel, DAG):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 167, in pydantic.utils.validate_field_name
NameError: Field name "dag_id" shadows a BaseModel attribute; use a different field name with "alias='dag_id'".
[2024-03-29T20:39:57.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:39:57.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.123 seconds
[2024-03-29T20:40:28.206+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:40:28.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:40:28.210+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:40:28.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:40:28.344+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:40:28.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 7, in <module>
    class GenericDAG(ABC, BaseModel, DAG):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 167, in pydantic.utils.validate_field_name
NameError: Field name "dag_id" shadows a BaseModel attribute; use a different field name with "alias='dag_id'".
[2024-03-29T20:40:28.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:40:28.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.216 seconds
[2024-03-29T20:40:58.596+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:40:58.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:40:58.599+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:40:58.598+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:40:58.642+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:40:58.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 7, in <module>
    class GenericDAG(ABC, BaseModel, DAG):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 167, in pydantic.utils.validate_field_name
NameError: Field name "dag_id" shadows a BaseModel attribute; use a different field name with "alias='dag_id'".
[2024-03-29T20:40:58.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:40:58.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.068 seconds
[2024-03-29T20:41:28.874+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:41:28.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:41:28.876+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:41:28.876+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:41:28.916+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:41:28.914+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 7, in <module>
    class GenericDAG(ABC, BaseModel, DAG):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 167, in pydantic.utils.validate_field_name
NameError: Field name "dag_id" shadows a BaseModel attribute; use a different field name with "alias='dag_id'".
[2024-03-29T20:41:28.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:41:28.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.067 seconds
[2024-03-29T20:41:59.157+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:41:59.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:41:59.160+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:41:59.159+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:41:59.203+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:41:59.200+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 7, in <module>
    class GenericDAG(ABC, BaseModel, DAG):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 167, in pydantic.utils.validate_field_name
NameError: Field name "dag_id" shadows a BaseModel attribute; use a different field name with "alias='dag_id'".
[2024-03-29T20:41:59.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:41:59.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.067 seconds
[2024-03-29T20:42:29.418+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:42:29.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:42:29.420+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:42:29.420+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:42:29.462+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:42:29.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 7, in <module>
    class GenericDAG(ABC, BaseModel, DAG):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 167, in pydantic.utils.validate_field_name
NameError: Field name "dag_id" shadows a BaseModel attribute; use a different field name with "alias='dag_id'".
[2024-03-29T20:42:29.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:42:29.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.062 seconds
[2024-03-29T20:46:18.164+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:46:18.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:46:18.167+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:46:18.167+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:46:19.023+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:46:19.016+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 18, in <module>
    class EmrAddStepsDAG(GenericDAG):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 22, in EmrAddStepsDAG
    validation_task_id: str = tasks.get("validation_task_id")
NameError: name 'tasks' is not defined
[2024-03-29T20:46:19.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:46:19.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 1.034 seconds
[2024-03-29T20:46:52.199+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:46:52.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:46:52.206+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:46:52.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:46:52.325+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:46:52.320+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 18, in <module>
    class EmrAddStepsDAG(GenericDAG):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 22, in EmrAddStepsDAG
    validation_task_id: str = tasks.get("validation_task_id")
NameError: name 'tasks' is not defined
[2024-03-29T20:46:52.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:46:52.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.176 seconds
[2024-03-29T20:47:22.572+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:47:22.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:47:22.576+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:47:22.575+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:47:22.638+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:47:22.636+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 18, in <module>
    class EmrAddStepsDAG(GenericDAG):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 22, in EmrAddStepsDAG
    validation_task_id: str = tasks.get("validation_task_id")
NameError: name 'tasks' is not defined
[2024-03-29T20:47:22.639+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:47:22.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.103 seconds
[2024-03-29T20:47:52.758+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:47:52.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:47:52.760+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:47:52.760+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:47:52.804+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:47:52.802+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 5, in <module>
    from highliner.builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 18, in <module>
    class EmrAddStepsDAG(GenericDAG):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 22, in EmrAddStepsDAG
    validation_task_id: str = tasks.get("validation_task_id")
NameError: name 'tasks' is not defined
[2024-03-29T20:47:52.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:47:52.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.073 seconds
[2024-03-29T20:54:57.735+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:54:57.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:54:57.739+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:54:57.739+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:54:57.885+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:54:57.858+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:54:57.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:54:57.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.225 seconds
[2024-03-29T20:55:29.173+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:55:29.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:55:29.217+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:55:29.217+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:55:29.437+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:55:29.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:55:29.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:55:29.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.353 seconds
[2024-03-29T20:55:59.720+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:55:59.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:55:59.723+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:55:59.723+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:55:59.825+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:55:59.820+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:55:59.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:55:59.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.138 seconds
[2024-03-29T20:56:30.027+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:56:30.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:56:30.030+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:56:30.030+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:56:30.092+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:56:30.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:56:30.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:56:30.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.084 seconds
[2024-03-29T20:57:00.358+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:57:00.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:57:00.361+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:57:00.361+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:57:00.423+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:57:00.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:57:00.423+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:57:00.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.086 seconds
[2024-03-29T20:57:30.650+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:57:30.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:57:30.653+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:57:30.653+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:57:30.718+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:57:30.716+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:57:30.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:57:30.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.089 seconds
[2024-03-29T20:58:00.932+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:58:00.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:58:00.935+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:58:00.935+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:58:00.990+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:58:00.985+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:58:00.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:58:01.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.078 seconds
[2024-03-29T20:58:31.154+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:58:31.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:58:31.156+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:58:31.156+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:58:31.204+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:58:31.202+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:58:31.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:58:31.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.067 seconds
[2024-03-29T20:59:01.466+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:59:01.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:59:01.469+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:59:01.469+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:59:01.524+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:59:01.522+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:59:01.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:59:01.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.087 seconds
[2024-03-29T20:59:31.767+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T20:59:31.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T20:59:31.771+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:59:31.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T20:59:31.837+0000] {logging_mixin.py:188} INFO - [2024-03-29T20:59:31.835+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 41, in build
    self.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 36, in validate
    return self.model_validate(self)
AttributeError: 'EmrAddStepsDAG' object has no attribute 'model_validate'
[2024-03-29T20:59:31.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T20:59:31.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.094 seconds
[2024-03-29T21:02:39.947+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:02:39.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:02:39.949+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:02:39.949+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:02:40.326+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:02:40.323+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:02:40.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:02:40.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.445 seconds
[2024-03-29T21:03:11.414+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:03:11.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:03:11.418+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:03:11.418+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:03:11.492+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:03:11.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:03:11.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:03:11.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.098 seconds
[2024-03-29T21:03:41.768+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:03:41.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:03:41.775+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:03:41.774+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:03:41.882+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:03:41.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:03:41.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:03:41.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.138 seconds
[2024-03-29T21:04:12.103+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:04:12.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:04:12.106+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:04:12.105+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:04:12.158+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:04:12.156+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:04:12.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:04:12.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.075 seconds
[2024-03-29T21:04:42.323+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:04:42.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:04:42.326+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:04:42.326+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:04:42.385+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:04:42.382+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:04:42.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:04:42.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.081 seconds
[2024-03-29T21:05:12.606+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:05:12.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:05:12.609+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:05:12.608+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:05:12.675+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:05:12.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:05:12.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:05:12.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.089 seconds
[2024-03-29T21:05:42.904+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:05:42.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:05:42.909+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:05:42.908+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:05:42.970+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:05:42.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:05:42.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:05:42.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.085 seconds
[2024-03-29T21:06:13.127+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:06:13.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:06:13.130+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:06:13.129+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:06:13.190+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:06:13.188+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:06:13.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:06:13.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.082 seconds
[2024-03-29T21:06:43.437+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:06:43.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:06:43.441+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:06:43.440+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:06:43.531+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:06:43.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:06:43.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:06:43.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.117 seconds
[2024-03-29T21:07:13.761+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:07:13.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:07:13.765+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:07:13.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:07:13.826+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:07:13.823+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:07:13.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:07:13.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.085 seconds
[2024-03-29T21:07:44.010+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:07:44.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:07:44.013+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:07:44.013+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:07:44.075+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:07:44.072+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 49, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 547, in __init__
    self.default_args["start_date"] = timezone.convert_to_utc(self.default_args["start_date"])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 104, in convert_to_utc
    if not is_localized(value):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 48, in is_localized
    return value.utcoffset() is not None
AttributeError: 'datetime.date' object has no attribute 'utcoffset'
[2024-03-29T21:07:44.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:07:44.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.085 seconds
[2024-03-29T21:09:19.314+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:09:19.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:09:19.316+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:09:19.316+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:09:19.690+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:09:19.687+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:09:19.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:09:19.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.398 seconds
[2024-03-29T21:09:50.339+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:09:50.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:09:50.347+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:09:50.346+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:09:50.530+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:09:50.521+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:09:50.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:09:50.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.243 seconds
[2024-03-29T21:10:20.908+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:10:20.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:10:20.915+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:10:20.914+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:10:21.040+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:10:21.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:10:21.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:10:21.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.161 seconds
[2024-03-29T21:10:51.258+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:10:51.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:10:51.261+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:10:51.261+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:10:51.320+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:10:51.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:10:51.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:10:51.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.080 seconds
[2024-03-29T21:11:21.469+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:11:21.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:11:21.472+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:11:21.471+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:11:21.529+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:11:21.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:11:21.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:11:21.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.083 seconds
[2024-03-29T21:11:51.741+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:11:51.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:11:51.745+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:11:51.744+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:11:51.815+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:11:51.813+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:11:51.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:11:51.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.097 seconds
[2024-03-29T21:12:22.083+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:12:22.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:12:22.086+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:12:22.086+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:12:22.151+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:12:22.147+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:12:22.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:12:22.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.087 seconds
[2024-03-29T21:12:52.364+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:12:52.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:12:52.367+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:12:52.367+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:12:52.427+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:12:52.425+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:12:52.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:12:52.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.083 seconds
[2024-03-29T21:13:22.555+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:13:22.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:13:22.558+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:13:22.558+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:13:22.619+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:13:22.616+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:13:22.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:13:22.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.092 seconds
[2024-03-29T21:13:52.834+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:13:52.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:13:52.837+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:13:52.837+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:13:52.894+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:13:52.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:13:52.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:13:52.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.085 seconds
[2024-03-29T21:14:23.130+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:14:23.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:14:23.133+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:14:23.133+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:14:23.197+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:14:23.194+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:14:23.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:14:23.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.091 seconds
[2024-03-29T21:14:53.404+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:14:53.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:14:53.407+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:14:53.407+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:14:53.461+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:14:53.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:14:53.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:14:53.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.083 seconds
[2024-03-29T21:15:23.669+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:15:23.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:15:23.672+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:15:23.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:15:23.730+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:15:23.727+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:15:23.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:15:23.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.079 seconds
[2024-03-29T21:15:53.846+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:15:53.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:15:53.849+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:15:53.848+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:15:53.905+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:15:53.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:15:53.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:15:53.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.086 seconds
[2024-03-29T21:16:24.118+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:16:24.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:16:24.121+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:16:24.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:16:24.180+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:16:24.177+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:16:24.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:16:24.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.085 seconds
[2024-03-29T21:16:54.372+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:16:54.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:16:54.375+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:16:54.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:16:54.431+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:16:54.428+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:16:54.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:16:54.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.079 seconds
[2024-03-29T21:17:24.632+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:17:24.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:17:24.637+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:17:24.636+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:17:24.705+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:17:24.701+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:17:24.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:17:24.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.092 seconds
[2024-03-29T21:17:54.799+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:17:54.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:17:54.802+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:17:54.801+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:17:54.859+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:17:54.855+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:17:54.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:17:54.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.087 seconds
[2024-03-29T21:18:25.085+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:18:25.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:18:25.091+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:18:25.090+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:18:25.172+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:18:25.169+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:18:25.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:18:25.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.128 seconds
[2024-03-29T21:18:55.392+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:18:55.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:18:55.395+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:18:55.395+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:18:55.459+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:18:55.456+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:18:55.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:18:55.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.094 seconds
[2024-03-29T21:19:25.692+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:19:25.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:19:25.695+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:19:25.694+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:19:25.748+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:19:25.745+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:19:25.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:19:25.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.080 seconds
[2024-03-29T21:19:55.957+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:19:55.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:19:55.960+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:19:55.959+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:19:56.019+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:19:56.016+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:19:56.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:19:56.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.085 seconds
[2024-03-29T21:20:26.214+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:20:26.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:20:26.217+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:20:26.216+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:20:26.273+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:20:26.270+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:20:26.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:20:26.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.084 seconds
[2024-03-29T21:20:56.472+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:20:56.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:20:56.476+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:20:56.475+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:20:56.533+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:20:56.531+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:20:56.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:20:56.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.086 seconds
[2024-03-29T21:21:26.736+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:21:26.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:21:26.739+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:21:26.739+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:21:26.807+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:21:26.804+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:21:26.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:21:26.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.101 seconds
[2024-03-29T21:21:57.025+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:21:57.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:21:57.027+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:21:57.027+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:21:57.093+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:21:57.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:21:57.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:21:57.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.092 seconds
[2024-03-29T21:22:27.208+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:22:27.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:22:27.211+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:22:27.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:22:27.268+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:22:27.265+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:22:27.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:22:27.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.081 seconds
[2024-03-29T21:22:57.479+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:22:57.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:22:57.482+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:22:57.482+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:22:57.546+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:22:57.543+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:22:57.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:22:57.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.092 seconds
[2024-03-29T21:23:27.756+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:23:27.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:23:27.759+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:23:27.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:23:27.822+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:23:27.819+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:23:27.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:23:27.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.093 seconds
[2024-03-29T21:23:58.035+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:23:58.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:23:58.038+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:23:58.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:23:58.092+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:23:58.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 16, in <module>
    DAGBuilder(dag_definitions).build_dags()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 13, in build_dags
    globals()[dag_id] = dag.build()
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 48, in build
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 527, in __init__
    date = timezone.parse(date)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timezone.py", line 213, in parse
    return pendulum.parse(string, tz=timezone or TIMEZONE, strict=strict)  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parser.py", line 43, in _parse
    parsed = base_parse(text, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 78, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/parsing/__init__.py", line 113, in _parse
    return parse_iso8601(text)
TypeError: argument 'input': 'date' object cannot be converted to 'PyString'
[2024-03-29T21:23:58.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:23:58.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.078 seconds
[2024-03-29T21:29:48.828+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:29:48.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:29:48.859+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:48.859+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:29:49.826+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-29T21:29:49.857+0000] {processor.py:840} INFO - DAG(s) 'exemple2', 'exemple1' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:29:50.771+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:50.770+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:exemple2
[2024-03-29T21:29:50.841+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:50.841+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:exemple2
[2024-03-29T21:29:50.935+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:50.934+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:exemple2
[2024-03-29T21:29:51.172+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:51.172+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:exemple1
[2024-03-29T21:29:51.267+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:51.266+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:exemple1
[2024-03-29T21:29:51.369+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:51.369+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:exemple1
[2024-03-29T21:29:51.373+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:51.372+0000] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-29T21:29:51.975+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:51.974+0000] {dag.py:3069} INFO - Creating ORM DAG for exemple1
[2024-03-29T21:29:51.976+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:51.976+0000] {dag.py:3069} INFO - Creating ORM DAG for exemple2
[2024-03-29T21:29:51.988+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:51.987+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple1 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:29:51.989+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:29:51.989+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple2 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:29:54.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 5.730 seconds
[2024-03-29T21:30:24.824+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:30:24.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:30:24.827+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:30:24.827+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:30:24.899+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-29T21:30:24.907+0000] {processor.py:840} INFO - DAG(s) 'exemple2', 'exemple1' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:30:24.937+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:30:24.937+0000] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-29T21:30:24.961+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:30:24.961+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple1 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:30:24.964+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:30:24.964+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple2 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:30:24.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.158 seconds
[2024-03-29T21:30:55.029+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:30:55.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:30:55.032+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:30:55.031+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:30:55.093+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-29T21:30:55.099+0000] {processor.py:840} INFO - DAG(s) 'exemple1', 'exemple2' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:30:55.121+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:30:55.121+0000] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-29T21:30:55.138+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:30:55.138+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple1 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:30:55.141+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:30:55.141+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple2 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:30:55.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.129 seconds
[2024-03-29T21:31:25.330+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:31:25.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:31:25.333+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:31:25.333+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:31:25.387+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-29T21:31:25.394+0000] {processor.py:840} INFO - DAG(s) 'exemple2', 'exemple1' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:31:25.418+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:31:25.418+0000] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-29T21:31:25.438+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:31:25.438+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple1 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:31:25.442+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:31:25.442+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple2 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:31:25.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.128 seconds
[2024-03-29T21:31:55.647+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:31:55.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:31:55.650+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:31:55.649+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:31:55.723+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-29T21:31:55.733+0000] {processor.py:840} INFO - DAG(s) 'exemple1', 'exemple2' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:31:55.758+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:31:55.758+0000] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-29T21:31:55.777+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:31:55.777+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple1 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:31:55.781+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:31:55.780+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple2 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:31:55.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.161 seconds
[2024-03-29T21:32:25.973+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T21:32:25.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T21:32:25.976+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:32:25.976+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T21:32:26.027+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py:437 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2024-03-29T21:32:26.034+0000] {processor.py:840} INFO - DAG(s) 'exemple2', 'exemple1' retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T21:32:26.055+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:32:26.054+0000] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-29T21:32:26.070+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:32:26.070+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple1 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:32:26.073+0000] {logging_mixin.py:188} INFO - [2024-03-29T21:32:26.073+0000] {dag.py:3834} INFO - Setting next_dagrun for exemple2 to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-03-29T21:32:26.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.127 seconds
[2024-03-29T23:04:20.321+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:04:20.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:04:20.324+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:04:20.324+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:04:20.414+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:04:20.397+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from highliner.utils import load_yaml
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/__init__.py", line 2, in <module>
    from .builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 6, in <module>
    from .registry import Registry
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 21, in <module>
    class Registry(metaclass=SingletonMeta):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 46, in Registry
    def get_registry(self) -> Dict[str, Dict[List[Dict[str, Any]]]]:
  File "/usr/local/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/typing.py", line 686, in __getitem__
    _check_generic(self, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/typing_extensions.py", line 167, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too few parameters for typing.Dict; actual 1, expected 2
[2024-03-29T23:04:20.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:04:20.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.163 seconds
[2024-03-29T23:04:51.326+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:04:51.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:04:51.330+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:04:51.330+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:04:51.502+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:04:51.480+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from highliner.utils import load_yaml
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/__init__.py", line 2, in <module>
    from .builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 6, in <module>
    from .registry import Registry
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 21, in <module>
    class Registry(metaclass=SingletonMeta):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 46, in Registry
    def get_registry(self) -> Dict[str, Dict[List[Dict[str, Any]]]]:
  File "/usr/local/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/typing.py", line 686, in __getitem__
    _check_generic(self, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/typing_extensions.py", line 167, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too few parameters for typing.Dict; actual 1, expected 2
[2024-03-29T23:04:51.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:04:51.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.240 seconds
[2024-03-29T23:05:21.761+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:05:21.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:05:21.763+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:05:21.763+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:05:21.809+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:05:21.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from highliner.utils import load_yaml
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/__init__.py", line 2, in <module>
    from .builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 6, in <module>
    from .registry import Registry
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 21, in <module>
    class Registry(metaclass=SingletonMeta):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 46, in Registry
    def get_registry(self) -> Dict[str, Dict[List[Dict[str, Any]]]]:
  File "/usr/local/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/typing.py", line 686, in __getitem__
    _check_generic(self, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/typing_extensions.py", line 167, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too few parameters for typing.Dict; actual 1, expected 2
[2024-03-29T23:05:21.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:05:21.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.064 seconds
[2024-03-29T23:05:52.048+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:05:52.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:05:52.050+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:05:52.049+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:05:52.093+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:05:52.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from highliner.utils import load_yaml
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/__init__.py", line 2, in <module>
    from .builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 6, in <module>
    from .registry import Registry
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 21, in <module>
    class Registry(metaclass=SingletonMeta):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 46, in Registry
    def get_registry(self) -> Dict[str, Dict[List[Dict[str, Any]]]]:
  File "/usr/local/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/typing.py", line 686, in __getitem__
    _check_generic(self, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/typing_extensions.py", line 167, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too few parameters for typing.Dict; actual 1, expected 2
[2024-03-29T23:05:52.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:05:52.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.071 seconds
[2024-03-29T23:06:22.337+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:06:22.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:06:22.339+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:06:22.338+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:06:22.384+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:06:22.381+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 3, in <module>
    from highliner.utils import load_yaml
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/__init__.py", line 2, in <module>
    from .builder import DAGBuilder
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/builder.py", line 2, in <module>
    from .models import EmrAddStepsDAG
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/models.py", line 6, in <module>
    from .registry import Registry
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 21, in <module>
    class Registry(metaclass=SingletonMeta):
  File "/home/airflow/.local/lib/python3.8/site-packages/highliner/registry.py", line 46, in Registry
    def get_registry(self) -> Dict[str, Dict[List[Dict[str, Any]]]]:
  File "/usr/local/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/typing.py", line 686, in __getitem__
    _check_generic(self, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/typing_extensions.py", line 167, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too few parameters for typing.Dict; actual 1, expected 2
[2024-03-29T23:06:22.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:06:22.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.064 seconds
[2024-03-29T23:09:43.224+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:09:43.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:09:43.228+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:09:43.228+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:09:43.315+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:09:43.313+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:09:43.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:09:43.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.115 seconds
[2024-03-29T23:10:13.811+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:10:13.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:10:13.817+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:10:13.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:10:14.053+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:10:14.050+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:10:14.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:10:14.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.305 seconds
[2024-03-29T23:10:44.368+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:10:44.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:10:44.374+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:10:44.373+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:10:44.492+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:10:44.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:10:44.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:10:44.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.156 seconds
[2024-03-29T23:11:14.711+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:11:14.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:11:14.715+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:11:14.714+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:11:14.783+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:11:14.780+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:11:14.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:11:14.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.094 seconds
[2024-03-29T23:11:45.003+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:11:45.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:11:45.008+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:11:45.007+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:11:45.085+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:11:45.083+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:11:45.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:11:45.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.103 seconds
[2024-03-29T23:12:15.299+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:12:15.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:12:15.302+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:12:15.302+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:12:15.361+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:12:15.359+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:12:15.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:12:15.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.079 seconds
[2024-03-29T23:12:45.539+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:12:45.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:12:45.557+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:12:45.556+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:12:45.694+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:12:45.691+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:12:45.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:12:45.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.203 seconds
[2024-03-29T23:17:48.617+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:17:48.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:17:48.623+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:17:48.621+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:17:48.964+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:17:48.953+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:17:48.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:17:49.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.544 seconds
[2024-03-29T23:18:20.829+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:18:20.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:18:20.832+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:18:20.831+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:18:20.919+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:18:20.918+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:18:20.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:18:20.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.112 seconds
[2024-03-29T23:18:51.162+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/build_dags.py
[2024-03-29T23:18:51.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/build_dags.py for tasks to queue
[2024-03-29T23:18:51.165+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:18:51.165+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/build_dags.py
[2024-03-29T23:18:51.224+0000] {logging_mixin.py:188} INFO - [2024-03-29T23:18:51.223+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/build_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/build_dags.py", line 13, in <module>
    path = job.get("path")
AttributeError: 'str' object has no attribute 'get'
[2024-03-29T23:18:51.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/build_dags.py
[2024-03-29T23:18:51.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/build_dags.py took 0.091 seconds
